#!/usr/bin/env node

/**
 * Email Notification Script for Monetly Task Completion
 * Uses nodemailer for reliable email delivery
 *
 * Setup:
 * 1. npm install nodemailer
 * 2. Set environment variables:
 *    export EMAIL_SERVICE="gmail"  # or "outlook", "yahoo", etc.
 *    export EMAIL_USER="your@email.com"
 *    export EMAIL_PASS="your-app-password"
 *    export EMAIL_TO="recipient@email.com"
 *
 * Usage: node scripts/notify-email.js "Subject" "Body text"
 */

const nodemailer = require('nodemailer');

// Configuration from environment variables
const config = {
  service: process.env.EMAIL_SERVICE || 'gmail',
  user: process.env.EMAIL_USER,
  pass: process.env.EMAIL_PASS,
  to: process.env.EMAIL_TO || 'pbparthas@gmail.com',  // Your email
};

// Validate configuration
if (!config.user || !config.pass) {
  console.error('❌ Email credentials not configured!');
  console.error('Set EMAIL_USER and EMAIL_PASS environment variables.');
  console.error('\nFor Gmail:');
  console.error('1. Enable 2FA in Google Account');
  console.error('2. Create App Password: https://myaccount.google.com/apppasswords');
  console.error('3. export EMAIL_USER="your@gmail.com"');
  console.error('4. export EMAIL_PASS="your-app-password"');
  process.exit(1);
}

// Get subject and body from command line args
const subject = process.argv[2] || 'Monetly Task Update';
const body = process.argv[3] || 'Tasks completed successfully.';

// Create transporter
const transporter = nodemailer.createTransport({
  service: config.service,
  auth: {
    user: config.user,
    pass: config.pass,
  },
});

// Email options
const mailOptions = {
  from: `Monetly Bot <${config.user}>`,
  to: config.to,
  subject: `Monetly: ${subject}`,
  text: body,
  html: `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 20px; border-radius: 8px 8px 0 0;">
        <h1 style="color: white; margin: 0;">💰 Monetly</h1>
      </div>
      <div style="background: #f8f9fa; padding: 30px; border-radius: 0 0 8px 8px;">
        <h2 style="color: #333; margin-top: 0;">${subject}</h2>
        <p style="color: #666; line-height: 1.6;">${body.replace(/\n/g, '<br>')}</p>
        <hr style="border: none; border-top: 1px solid #ddd; margin: 20px 0;">
        <p style="color: #999; font-size: 12px;">
          Generated by Monetly Task Automation<br>
          ${new Date().toLocaleString()}
        </p>
      </div>
    </div>
  `,
};

// Send email
transporter.sendMail(mailOptions, (error, info) => {
  if (error) {
    console.error('❌ Failed to send email:', error.message);
    process.exit(1);
  } else {
    console.log('✅ Email notification sent successfully!');
    console.log(`   To: ${config.to}`);
    console.log(`   Subject: Monetly: ${subject}`);
    console.log(`   Message ID: ${info.messageId}`);
  }
});
